"use strict";
window.GoldAuth=(function(){
  const localUsersKey="emerald_gold_local_users";
  const hash=async text=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text)))).map(b=>b.toString(16).padStart(2,"0")).join("");
  const readUsers=()=>{try{return JSON.parse(localStorage.getItem(localUsersKey)||"{}")}catch{return {}}};
  const saveUsers=u=>localStorage.setItem(localUsersKey,JSON.stringify(u));
  async function firebase(){try{return await import("./firebase.js")}catch(e){console.warn("Firebase unavailable",e);return null}}
  async function findCloudUser(username){const fb=await firebase();if(!fb?.db)return null;for(const collectionName of ["emeraldOSUsers","users"]){try{const snap=await fb.getDoc(fb.doc(fb.db,collectionName,username));if(snap.exists())return {...snap.data(),__collection:collectionName}}catch(e){console.warn(e)}}return null}
  async function login(username,password){username=String(username||"").trim();if(!username||!password)throw new Error("Enter your username and password.");const passwordHash=await hash(password),cloud=await findCloudUser(username);if(cloud){if(cloud.locked)throw new Error(cloud.lockReason||"This account is locked.");if(String(cloud.passwordHash||"").toLowerCase()!==passwordHash)throw new Error("Incorrect username or password.");return {username:cloud.username||username,role:cloud.role||"user",role2:cloud.role2||"User",userId:cloud.userId||username,cloud:true}}
    const users=readUsers(),u=users[username.toLowerCase()];if(!u||u.passwordHash!==passwordHash)throw new Error("Incorrect username or password.");if(u.locked)throw new Error(u.lockReason||"This account is locked.");return {...u,username:u.username||username,cloud:false};
  }
  async function register(username,password,displayName){username=String(username||"").trim();if(!/^[A-Za-z0-9._-]{3,32}$/.test(username))throw new Error("Use 3–32 letters, numbers, periods, underscores, or hyphens.");if(String(password).length<6)throw new Error("Use a password with at least 6 characters.");if(await findCloudUser(username))throw new Error("That username is already registered.");const users=readUsers();if(users[username.toLowerCase()])throw new Error("That username is already registered.");const record={username,displayName:displayName||username,passwordHash:await hash(password),role:"user",role2:"User",locked:false,created:new Date().toISOString(),lastUpdated:new Date().toISOString(),userId:username};users[username.toLowerCase()]=record;saveUsers(users);const fb=await firebase();if(fb?.db){try{await fb.setDoc(fb.doc(fb.db,"emeraldOSUsers",username),record,{merge:true})}catch(e){console.warn("Cloud registration blocked; local account retained",e)}}return record}
  function beginSession(user){localStorage.setItem("loggedIn","true");localStorage.setItem("gold1g_loggedIn","true");localStorage.setItem("username",user.username);localStorage.setItem("gold1g_username",user.username);localStorage.setItem("role",user.role||"user");localStorage.setItem("role2",user.role2||"User");localStorage.setItem("userId",user.userId||user.username);localStorage.setItem("gold1h_last_login",new Date().toISOString())}
  return {hash,login,register,beginSession,findCloudUser,readUsers};
})();
